// frontend/src/comps/pages/home.svelte
<script lang="ts">
	import type { Category } from '@prisma/client';

	import { onMount } from 'svelte';
	//import { cats } from '../../appStore';
	import fetchApi from '../../helpers/api';
	import queryList from '../../helpers/queryList';

	let loadedCats: Category[] = [];

	//cats.subscribe((value) => (loadedCats = value));

	onMount(async () => {
		
		let res = await fetchApi(queryList.allCategories, {});
		//cats.load(res);
		loadedCats = res

		return () => {};
	});
</script>

<main>
	{#each loadedCats as c}
		{c.name}<br />
	{/each}
</main>

// client/src/components/pages/home.tsx
import { Category, User } from '@prisma/client';
import { useEffect, useState } from 'react';
import useApi from '../../helpers/useApi';
import queryList from '../../queryList';
import AddCategoryForm from '../widgets/addCategoryForm';
import CategoryList from '../widgets/categoryList';
import UserList from '../widgets/userList';

interface IHomePageProps {}

export const HomePage: React.FC<IHomePageProps> = (props) => {
	const { fetchApi } = useApi();
	const [allUsers, setAllUsers] = useState<User[]>([]);
	const [allCategories, setAllCategories] = useState<Category[]>([]);

	useEffect(() => {
		fetchApi(queryList.allUsers, {}).then((res) => {
			setAllUsers(res);
			fetchApi(queryList.allCategories, {}).then((res2) =>
				setAllCategories(res2)
			);
		});
	}, []);

	return (
		<div>
			Hello World.
			<UserList users={allUsers} />
			<CategoryList cats={allCategories} />
			<AddCategoryForm />
		</div>
	);
};
